INSERT INTO GAPP_CLASS(name) values ('first class')

INSERT INTO GAPP_USER (username, password, role, GAPP_CLASS_ID) values ('admin','$2y$12$KWV9Ung46ypGm6iu30Zc9uZQeWNMysvMJaQ4Gk.JhnidAp3U9L.Em','ADMIN',1)
INSERT INTO GAPP_USER (username, password, role, GAPP_CLASS_ID) values ('user','$2y$12$F16RoAW86fvzz0tDlWR76edMlSf457pBCrMaRj7N5thEqQAO33432','USER',1)

INSERT INTO GAPP_EXERCISE (ANSWER, TYPE, MATERIALS, QUESTION) VALUES ('my answer','question','materials123','what is the answer?')
INSERT INTO GAPP_EXERCISE (ANSWER, TYPE, MATERIALS, QUESTION) VALUES ('wisla','question','wisla,bug,odra,ropa','ktora polska rzeka jest najdluzsza?')
INSERT INTO GAPP_EXERCISE (ANSWER, TYPE, MATERIALS, QUESTION) VALUES ('krakow','question','krakow,warszawa,gdansk','ktore z miast znajduje sie w malopolsce?')

INSERT INTO GAPP_TASK (NAME) VALUES ('first task')
INSERT INTO GAPP_TASK_GAPP_EXERCISE (GAPP_TASK_ID,GAPP_EXERCISE_ID) VALUES (1,1)
INSERT INTO GAPP_TASK_GAPP_EXERCISE (GAPP_TASK_ID,GAPP_EXERCISE_ID) VALUES (1,2)

INSERT INTO GAPP_TASK (NAME) VALUES ('second task')
INSERT INTO GAPP_TASK_GAPP_EXERCISE (GAPP_TASK_ID,GAPP_EXERCISE_ID) VALUES (2,3)

INSERT INTO GAPP_ASSIGNMENT (DUE_DATE,GAPP_TASK_ID) VALUES (parsedatetime('01-01-2021','dd-MM-yyyy'),1)
INSERT INTO GAPP_ASSIGNMENT (DUE_DATE,GAPP_TASK_ID) VALUES (parsedatetime('01-01-2021','dd-MM-yyyy'),2)

INSERT INTO GAPP_MARK (IS_PASS_FAIL,MARK_VALUE,GAPP_ASSIGNMENT_ID, GAPP_USER_ID) VALUES (FALSE,75,1,1)

INSERT INTO GAPP_CLASS_GAPP_ASSIGNMENTS (GAPP_CLASS_ID, GAPP_ASSIGNMENTS_ID) VALUES (1,1)